version: '3.4'

services:
	bookservice: 
		image: bookservice:latest
		build:
			context: /
			dockerfile: Services/Books/Dockerfile

	searchservice: 
		image: searchservice:latest
		build:
			context: /
			dockerfile: Services/Search/Dockerfile

networks:
	savedbooksnetwork:
		driver: bridge
		ipam: 
			driver: default
			config:
				
